values = {
    "start_crawl_page": "https://www.allocine.fr/film/aucinema/",
    "css_movie_url": "h2.meta-title a.meta-title-link",
    "css_crawl_more": "nav.pagination.cf div.pagination-item-holder a.button.button-md.item",
    "css_page_title": "div.titlebar",
    "css_casting_url": "a[title='Casting']",
    "css_presse_rating": "div.rating-holder.rating-holder-3 div.rating-item div.rating-item-content div.stareval.stareval-medium.stareval-theme-default span.stareval-note",
    "css_public_rating": "div.rating-holder.rating-holder-3 div.rating-item div.rating-item-content div.stareval.stareval-medium.stareval-theme-default span.stareval-note",
    "css_ratings": "div.rating-item-content .stareval-note",
    "css_original_title": "div.meta div.meta-body div.meta-body-item span.light",
    "css_synopsis": "section#synopsis-details div.content-txt",
    "css_cities": "div.gd-col-left section.section.ovw div.mdl-more.gd.small-crop",
    "css_date": "div.meta div.meta-body div.meta-body-item.meta-body-info .date",
    "css_meta": "div.meta div.meta-body div.meta-body-item.meta-body-info",
    "css_directors": "section.section.casting-director a.meta-title-link",
    "css_writers": "div.section.casting-list-gql a.xXx.item.link",
    "css_actors": "section.section.casting-actor a.meta-title-link, section.section.casting-actor a.item.link",
    "css_sound_track": "div.section.casting-list-gql a.item.link",
    "css_public_critic_url": "a[title='Critiques spectateurs']",
    "css_pro_critic_url": "a[title='Critiques presse']",
    "css_note": "div.big-note span.note",
    "css_pro_critic_note": "span.stareval-note",
    "css_everyone": ".item.link",
    "css_poster": "img.thumbnail-img"
}
